package constants

const ServiceDir = "/lib/systemd/system"
const ServiceDirSoftLink = "/etc/systemd/system/multi-user.target.wants"

const GitHubOwner = "NubeIO"
const SettingUUID = "set_123456789ABC"
const Eth0 = "eth0"
const Eth1 = "eth1"
const ConfigYml = "config.yml"
const BacnetServerDriver = "driver-bacnet"
const BacnetServerServiceName = "nubeio-driver-bacnet"
const RubixEdgeWiresServiceName = "nubeio-rubix-edge-wires"
const RubixIO16Repo = "rubix-io-fw"
const Edge28App = "driver-edge28"
const RubixIOApp = "driver-rubix-compute-io"
const RubixIOAppServiceName = "nubeio-driver-rubix-compute-io"
const RubixEdgeWires = "rubix-edge-wires"
const RubixOs = "rubix-os"
const RubixOsServiceName = "nubeio-rubix-os.service"
const RubixWires = "rubix-wires"
const LoRaSerialApp = "driver-lora"
const LoRaSerialAppServiceName = "nubeio-driver-lora"
const LoRaModbusBrideApp = "lorawan-modbus-bridge"
const LoRaModbusBrideAppServiceName = "nubeio-lorawan-modbus-bridge"
const RubixOsReleasesRepo = "rubix-os-releases"
const RubixOsVersionsPath = "versions"
const LatestTag = "latest"

const CSUname = "admin"
const CSPassword = "Helensburgh2508"

const UserAdminToken = "Helensburgh2508"
